name: Daily Agent arXiv Update
on:
  schedule:
    # 对应 EDT：00:00 UTC（= 前一天 20:00 ET），周一到周五
    - cron: '10 0 * * 1-5'
    # 对应 EST：01:00 UTC（= 前一天 20:00 ET），周一到周五
    - cron: '10 1 * * 1-5'
  workflow_dispatch:  # Allow manual triggering

# 添加权限设置
permissions:
  contents: write
  actions: read

jobs:
  update-papers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # 明确指定token
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run daily update
      run: |
        python daily_arxiv.py
        
    - name: Check if there are changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Daily update: $(date '+%Y-%m-%d')" || exit 0
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
